spring.datasource:
   # userSSL=false 表示不使用加密通讯，本机的数据库没有必要加密
   # serverTimezone=CST表示指定服务器的时区，CST=China Standard Time
   url: jdbc:mysql://localhost:3306/kemao_2?userSSL=false&serverTimezone=CST
   username: kemao_2
   password: 1234

   
#指定服务器在运行的时候，Tomcat使用的端口
#Spring Boot自带了一个阉割版Tomcat，默认不支持JSP，只支持Servlet   
server.port: 8090
